import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// ↓ 追加
import Navbar from "./components/Navbar"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "売買和達 - AIフリマ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Navbar /> {/* ← これを追加！ */}
        {children}
      </body>
    </html>
  );
}